# Generated by Django 4.0.5 on 2022-06-30 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Blog',
            new_name='blog',
        ),
    ]
