# Generated by Django 4.0.4 on 2022-07-20 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_comment2_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='test_list',
            field=models.TextField(null=True),
        ),
    ]
