# Generated by Django 4.0.4 on 2022-07-20 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_blog_price_remove_post_price_blog_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='summary',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
