# Generated by Django 4.0.6 on 2022-07-25 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
