# Generated by Django 4.0.6 on 2022-07-26 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_dislike_like_blog_dislike_user_set_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='writer',
        ),
        migrations.DeleteModel(
            name='Comment2',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
